import { Navbar, Footer } from "@/components/layout";
import { ScrollButton } from "@/components/elements";
import "../styles/main.scss";

export const metadata = {
  title: 'Dentalist | With Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
      
        <Navbar/>
        <main>
        <ScrollButton/>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
