import { Navbar, Footer } from "@/components/layout";
import { ScrollButton } from "@/components/elements";
import "../styles/main.scss";

export const metadata = {
  metadataBase: new URL('https://dentalist-web-app-nextjs.vercel.app/'),
  openGraph: {
    title: 'Dentalist | With Next.js',
    description: 'Generated by create next app',
    creator: '@martinedev_',
    images: [
      {
        url: "/Screenshot_1.png",
        width: 800,
        height: 600,
      }
    ]
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar/>
        <main>
        <ScrollButton/>
          {children}
        </main>
        <Footer/> 
      </body>
    </html>
  )
}
